# Introduction {.unnumbered}

Overview of the ggplot2 package and what it does.
Explanation of grammar of graphics and its layering characteristics.
Include a short example script.

Objective of this project in identifying packages and mapping out the environment.
**Overview of the following sections.

Future directions.

---

The ggplot2 package is a powerful tool for data visualization in R, built on the principles of the Grammar of Graphics[^1]. ggplot2 facilitates the layering of independent components to build up plots step by step, offering a high degree of customization.

The Grammar of Graphics, as implemented by ggplot2, breaks down plots into components such as scales (mapping data to aesthetics), geoms (geometric objects), stats (statistical transformations), and facets (panels). This approach enables users to structurally layer these components to build up the final plot. For example, a user can start by defining the data and aesthetics (aes), add layers of geoms for different data representations, and further refine the plot with scales and themes.

Here’s a brief example to illustrate how ggplot2 is used:
```{r}
library(ggplot2)

ggplot(mpg, aes(displ, hwy, colour = class)) + 
  geom_point() +
  scale_fill_discrete()
```

Many packages have been developed to extend the functionality of ggplot2, enhancing its capabilities and ease of use. These extensions are available publicly and contribute to a large ecosystem around ggplot2. Examples include ggmap for integrating maps into graphics, patchwork for arranging multiple plots, and ggthemes for new theme and scale options. This environment fosters continuous and openly communicated innovation.

The objective of this project was to explore the vast ecosystem surrounding the ggplot2 package, focusing on identifying and cataloging the various package extensions that enhance or complement its functionality. The first phase involved gathering and collecting download data for (to assess popularity) packages within the ggplot2 ecosystem. Subsequently, I began to explore and categorize these packages to demonstrate how they support data visualization tasks.

This project also served as an opportunity to learn and refine practical skills in managing a project. I learned to utilized tools such as GitHub for version control and how to organize scripts and code effectively. By actively using ggplot2 and its principles throughout the project, I was able to enhance my data visualization skills, creating detailed graphical representations of data.

Looking ahead, the next steps for this project involve a more complete mapping of the ggplot2 ecosystem, identifying and classifying all packages and exploring trends in data visualization that could further enhance functionality and user experience. This comprehensive mapping will provide a more robust starting point and framework for users to find tools for their specific data visualization needs.

This ongoing work will continue to enrich the community's resources and foster an environment of continued innovation and collaboration in data visualization.

[^1] https://ggplot2.tidyverse.org/
[^2]

